site_name: CHS Knowledge Hub
theme:
  name: material

plugins:
  - search
  - tags
  - mkdocs-pyscript
  - mkdocstrings:
      handlers:
        python:
          paths: [../water_system_sdk/src]
          options:
            show_root_heading: yes
            show_source: yes
  - autorefs

nav:
  - '首页': 'index.md'
  - '部署指南': 'deployment_guide.md'
  - '教程':
    - '入门教程': 'sdk_tutorials/getting_started.md'
    - '核心模型指南':
      - '线性水库 (LinearTank)': 'notebooks/02_Core_Model_LinearTank.ipynb'
      - '非线性水库 (NonlinearTank)': 'notebooks/03_Core_Model_NonlinearTank.ipynb'
      - '马斯京根模型 (Muskingum)': 'notebooks/04_Core_Model_Muskingum.ipynb'
      - 'SCS产流模型 (SCSRunoff)': 'notebooks/05_Hydrology_SCSRunoff.ipynb'
      - '新安江模型 (Xinanjiang)': 'notebooks/06_Hydrology_Xinanjiang.ipynb'
      - '产流系数法 (RunoffCoefficient)': 'notebooks/07_Hydrology_RunoffCoefficient.ipynb'
    - '高级教程':
      - '使用MPC进行预测控制': 'sdk_tutorials/advanced_mpc.md'
      - '多智能体协同': 'sdk_tutorials/multi_agent_collaboration.md'
      - '硬件在环(HIL)测试': 'sdk_tutorials/hil_testing.md'
      - '创建自定义智能体': 'sdk_tutorials/creating_a_custom_agent.md'
  - '智能体动物园': 'agent_zoo.md'
  - '案例研究':
    - '概述': 'case_studies/index.md'
    - '梯级水库联合调度': 'case_studies/cascade_reservoir_optimization.md'
  - 'API 参考':
    - '核心智能体': 'api_reference/core_agents.md'
    - 'Host': 'api_reference/host.md'
    - 'Modeling': 'api_reference/modeling.md'
    - 'SCADA Dispatch API': 'api_reference/scada_dispatch_api.md'
    - 'Twin Factory API': 'api_reference/twin_factory_api.md'
  - '社区':
    - '社区中心': 'community.md'
    - '贡献指南': 'contributing.md'
