site_name: CHS Knowledge Hub
theme:
  name: material

plugins:
  - search
  - tags
  - mkdocs-pyscript
  - mkdocstrings:
      handlers:
        python:
          paths: [../water_system_sdk/src]
          options:
            show_root_heading: yes
            show_source: yes
  - autorefs

nav:
  - '首页': 'index.md'
  - '部署指南': 'deployment_guide.md'
  - '案例教程':
    - '基础PID控制': 'notebooks/19_Example_Simple_PID.ipynb'
    - '高级MPC对比': 'notebooks/20_Example_MPC_Comparison.ipynb'
  - '数据预处理指南':
    - '降雨插值 (RainfallProcessor)': 'notebooks/15_Preprocessing_Rainfall.ipynb'
    - 'DEM与流域划分 (Watershed Delineation)': 'notebooks/16_Preprocessing_DEM.ipynb'
  - '教程':
    - '入门教程': 'sdk_tutorials/getting_started.md'
    - '核心模型指南':
      - '线性水库 (LinearTank)': 'notebooks/02_Core_Model_LinearTank.ipynb'
      - '非线性水库 (NonlinearTank)': 'notebooks/03_Core_Model_NonlinearTank.ipynb'
      - '马斯京根模型 (Muskingum)': 'notebooks/04_Core_Model_Muskingum.ipynb'
      - 'SCS产流模型 (SCSRunoff)': 'notebooks/05_Hydrology_SCSRunoff.ipynb'
      - '新安江模型 (Xinanjiang)': 'notebooks/06_Hydrology_Xinanjiang.ipynb'
      - '产流系数法 (RunoffCoefficient)': 'notebooks/07_Hydrology_RunoffCoefficient.ipynb'
      - 'PID控制器 (PIDController)': 'notebooks/08_Control_PIDController.ipynb'
      - '模型预测控制 (MPCController)': 'notebooks/09_Control_MPCController.ipynb'
      - '一维水动力学 (StVenant)': 'notebooks/10_Hydrodynamics_StVenant.ipynb'
      - '二维水动力学 (2D Hydro)': 'notebooks/14_Hydrodynamics_2D.ipynb'
    - '高级教程':
      - '使用MPC进行预测控制': 'sdk_tutorials/advanced_mpc.md'
      - '多智能体协同': 'sdk_tutorials/multi_agent_collaboration.md'
      - '硬件在环(HIL)测试': 'sdk_tutorials/hil_testing.md'
      - '创建自定义智能体': 'sdk_tutorials/creating_a_custom_agent.md'
  - '系统辨识指南':
    - '递归最小二乘法 (RLS)': 'notebooks/17_SysID_RLS.ipynb'
    - '卡尔曼滤波 (Kalman Filter)': 'notebooks/18_SysID_KalmanFilter.ipynb'
  - '扰动与事件指南':
    - '时间序列扰动 (TimeSeries)': 'notebooks/11_Disturbances_TimeSeries.ipynb'
    - '降雨事件 (RainfallAgent)': 'notebooks/12_Disturbances_Rainfall.ipynb'
    - '系统故障 (FaultAgent)': 'notebooks/13_Disturbances_Faults.ipynb'
  - '智能体动物园': 'agent_zoo.md'
  - '案例研究':
    - '概述': 'case_studies/index.md'
    - '梯级水库联合调度': 'case_studies/cascade_reservoir_optimization.md'
  - 'API 参考':
    - '核心智能体': 'api_reference/core_agents.md'
    - 'Host': 'api_reference/host.md'
    - 'Modeling': 'api_reference/modeling.md'
    - 'SCADA Dispatch API': 'api_reference/scada_dispatch_api.md'
    - 'Twin Factory API': 'api_reference/twin_factory_api.md'
  - '社区':
    - '社区中心': 'community.md'
    - '贡献指南': 'contributing.md'
