# scenarios/case_centralized_mpc/config.yaml

simulation_settings:
  duration_seconds: 3600  # Simulate for 1 hour
  time_step: 60           # Time step of 1 minute

agent_society:
  # ==================================================
  # 1. 战略调度大脑 (集中式 MPC)
  # ==================================================
  - id: central_dispatch_brain
    class: water_system_simulator.agent.dispatch_agent.DispatchAgent
    params:
      mode: 'centralized_mpc'
      # 该智能体为整个系统做出高层决策
      # 它订阅关键系统状态并发布宏观指令
      subscribes_to:
        - data.level.tank_1
        - data.level.tank_2
        - data.inflow.main_river
      publishes_to:
        - cmd.macro.control_tank_1
        - cmd.macro.control_tank_2

  # ==================================================
  # 2. 战术执行单元 (现地 PID 控制器)
  # ==================================================
  - id: pid_controller_1
    class: chs_sdk.agents.control_agents.PIDAgent
    params:
      Kp: 1.2
      Ki: 0.1
      Kd: 0.05
      set_point: 5.0
      input_topic: "data.level.tank_1"
      output_topic: "cmd.opening.valve_1"

  - id: pid_controller_2
    class: chs_sdk.agents.control_agents.PIDAgent
    params:
      Kp: 1.0
      Ki: 0.12
      Kd: 0.04
      set_point: 4.5
      input_topic: "data.level.tank_2"
      output_topic: "cmd.opening.valve_2"

  # ==================================================
  # 3. 物理系统的数字孪生 (本体智能体)
  # ==================================================
  - id: main_inflow_source
    class: chs_sdk.agents.disturbance_agents.InflowAgent
    params:
      topic: "data.inflow.main_river"
      rainfall_pattern: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

  - id: storage_tank_1
    class: chs_sdk.agents.body_agents.TankAgent
    params:
      area: 100.0
      initial_level: 5.0
      # 该水箱的水位受主要入流及其出口阀门的影响
      subscribes_to:
        - data.inflow.main_river
        - state/valve/outlet_valve_1
      publishes_to: data.level.tank_1

  - id: outlet_valve_1
    class: chs_sdk.agents.body_agents.ValveAgent
    params:
      cv: 0.5
      # 该阀门的开度由其对应的PID控制器控制
      subscribes_to:
        - cmd.opening.valve_1

  - id: storage_tank_2
    class: chs_sdk.agents.body_agents.TankAgent
    params:
      area: 120.0
      initial_level: 4.5
      subscribes_to:
        - data.inflow.main_river
        - state/valve/outlet_valve_2
      publishes_to: data.level.tank_2

  - id: outlet_valve_2
    class: chs_sdk.agents.body_agents.ValveAgent
    params:
      cv: 0.45
      subscribes_to:
        - cmd.opening.valve_2
