# System topology for Case 3: One Gate, One Channel with MPC Control
# NOTE: This uses a simplified linear model for the MPC's internal prediction.

components:
  - name: inflow_to_channel
    type: Disturbance

  - name: channel
    type: MuskingumChannelModel
    properties:
      K: 5.0
      x: 0.2
      dt: 1.0
      initial_inflow: 10.0
      initial_outflow: 10.0
    connections:
      inflow_current: inflow_to_channel.output

  - name: mpc_controller
    type: MPCController
    properties:
      A: [[1.0]]
      B: [[-1.0]]
      Q: [[1.0]]
      R: [[0.5]]
      N: 10
      setpoint: [10.0]
      u_min: 0.0
      u_max: 10.0
    connections:
      measured_value: channel.output

  - name: gate
    type: GateModel
    properties:
      discharge_coefficient: 0.6
      area: 1.0 # Initial area
    connections:
      upstream_level: channel.output
      downstream_level: 5.0
      area: mpc_controller.output

logging:
  - time
  - channel.output
  - gate.output # Flow through the gate
  - mpc_controller.output # Gate area
  - inflow_to_channel.output
