# System topology for Case 1: Single-Tank System

components:
  - name: pid_controller
    type: PIDController
    properties:
      kp: 1.5
      ki: 0.05
      kd: 1.0
      setpoint: 1.0
    connections:
      # The input to the PID controller is the storage level of tank1
      measured_value: tank1.storage

  - name: tank1
    type: FirstOrderInertiaModel
    properties:
      initial_storage: 0.5
      time_constant: 5.0  # Represents outflow resistance
    connections:
      # The input to the tank is the output of the pid_controller
      inflow: pid_controller.output

logging:
  - time
  - tank1.storage
  - tank1.output  # The output of the step method is the outflow
  - pid_controller.output
