# System topology for Case 4: Distant Downstream Control PID

components:
  - name: upstream_inflow
    type: Disturbance

  - name: downstream_demand
    type: Disturbance

  - name: upstream_channel
    type: IntegralDelayModel
    properties:
      initial_outflow: 10.0
      delay_steps: 5
    connections:
      inflow: upstream_inflow.output

  - name: pid_controller_downstream
    type: PIDController
    properties:
      kp: -0.05 # Smaller gains due to long delay
      ki: -0.005
      kd: -0.01
      setpoint: 8.0 # Target for the downstream channel's end level
    connections:
      measured_value: downstream_channel.output

  - name: gate
    type: GateModel
    properties:
      discharge_coefficient: 0.6
      area: 1.0 # Initial area
    connections:
      upstream_level: upstream_channel.output
      downstream_level: 8.0
      area: pid_controller_downstream.output

  - name: net_inflow_calculator
    type: SummingPoint
    connections:
      - gate.output
      - downstream_demand.output
    gains: [1, -1]

  - name: downstream_channel
    type: IntegralDelayModel
    properties:
      initial_outflow: 8.0
      delay_steps: 8
    connections:
      inflow: net_inflow_calculator.output

logging:
  - time
  - upstream_channel.output
  - downstream_channel.output
  - pid_controller_downstream.output # Gate area
  - upstream_inflow.output
  - downstream_demand.output
