# System topology for Case 4: Local Upstream Control PID

components:
  - name: upstream_inflow
    type: Disturbance

  - name: downstream_demand
    type: Disturbance

  - name: upstream_channel
    type: IntegralDelayModel
    properties:
      initial_outflow: 10.0
      delay_steps: 5
    connections:
      inflow: upstream_inflow.output

  - name: pid_controller_upstream
    type: PIDController
    properties:
      kp: -0.1 # Control for upstream level
      ki: -0.01
      kd: -0.02
      setpoint: 10.0
    connections:
      measured_value: upstream_channel.output

  - name: gate
    type: GateModel
    properties:
      discharge_coefficient: 0.6
      area: 1.0 # Initial area
    connections:
      upstream_level: upstream_channel.output
      downstream_level: 8.0 # Assume a constant level just downstream of the gate
      area: pid_controller_upstream.output

  - name: net_inflow_calculator
    type: SummingPoint
    connections:
      - gate.output
      - downstream_demand.output
    gains: [1, -1] # net_inflow = gate_flow - demand

  - name: downstream_channel
    type: IntegralDelayModel
    properties:
      initial_outflow: 8.0
      delay_steps: 8
    connections:
      inflow: net_inflow_calculator.output

logging:
  - time
  - upstream_channel.output # Gate forebay level
  - downstream_channel.output # Downstream channel end level
  - pid_controller_upstream.output # Gate area
  - upstream_inflow.output
  - downstream_demand.output
